### ISSUE TITLE
使用时出现Unknown error occurred错误

### ISSUE THREAD

**Issue by LeoWang2007** [qwe7989199/aegisub_scripts#10]
aegisub版本3.2.2 32位
消极压制版本v0.4.1

先前使用releases中的 _年度更新版_ **出现 https://github.com/qwe7989199/aegisub_scripts/issues/8 中的错误**

现在使用code中的版本，**没有出现** https://github.com/qwe7989199/aegisub_scripts/issues/8 中的错误，但是导致**出现Unknown error occurred错误**
![图片](https://user-images.githubusercontent.com/79351490/163676470-0cdc1ad7-6ac7-4e67-9381-8d6ad454443f.png)

麻烦指导解决一下，谢谢！

**Comment by qwe7989199** [comment]
取消勾选delete avs，贴一下avs文件内容

**Comment by LeoWang2007** [comment]
```
LoadPlugin("D:\Desktop\subtitle\NegativeEncoder\Libs\vapoursynth64\plugins\vsfilter.dll")
MaskSub("D:\Desktop\sub\sub.ass",1920,1080,30.000,1000).FlipVertical()
assumefps(30.000000)
```

**Comment by qwe7989199** [comment]
> 
确保avisynth和ffmpeg版本对应，同为32bit 或 64bit
直接通过ffmpeg输入上面的avs进行编码，如果依旧报错，就不是本仓库里的脚本该解决的问题了
因为相当于自己手写一个avs也跑不通
换个avs或者ff解决吧

**Comment by LeoWang2007** [comment]
新手，可以再追问一下吗

avisynth是哪个软件，怎么查看版本
我就装了三样东西
1. 消极压制
2. Aegisub
3. 你的插件

**Comment by qwe7989199** [comment]
> 新手，可以在追问一下吗
> 
> avs是哪个文件 我就装了三样东西
> 
> 1. 消极压制
> 2. Aegisub
> 3. 你的插件
引用自readme

> 使用 vapoursynth+x264/NVEnc/QSVEnc/VCEEnc 中的一种进行视频压制(硬字幕)。
> 或者将字幕压制为透明通道的mov文件(或双mp4文件),依赖于ffmpeg和Avisynth(测试于Avisynth+ r2772,64bit为必须)。

这说明只有两行，建议搞懂运行这个脚本究竟需要什么东西，都是在github一搜就有的东西，因为支持的版本不唯一，所以没必要贴下载链接，按readme操作即可

傻瓜工具就是按说明书操作就好，说明书不看，没人能救

**Comment by LeoWang2007** [comment]
已解决，谢谢！
