### ISSUE TITLE
请教一下CNSpellChecker.lua依赖怎么用

### ISSUE THREAD

**Issue by tianziabcd** [qwe7989199/aegisub_scripts#11]
请问，下载依赖lua到\Aegisub\automation文件夹下报错

**Comment by qwe7989199** [comment]
没有报错，无效提问

**Comment by tianziabcd** [comment]
那应该是不会安装依赖造成的报错，请教一下依赖要怎么安装呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月26日(星期二) 中午12:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qwe7989199/aegisub_scripts] 请教一下CNSpellChecker.lua依赖怎么用 (Issue #11)





 
没有报错，无效提问

**Comment by qwe7989199** [comment]
去对应仓库下载lua和release中的dll文件
dll放在aegisub根目录
lua放在automation\include目录下

**Comment by tianziabcd** [comment]
[luajit-request](https://github.com/LPGhatguy/luajit-request/tree/master/luajit-request)release中未曾找到dll文件

**Comment by tianziabcd** [comment]
19:53:02: A script in the Automation autoload directory failed to load.
Please review the errors, fix them and use the Rescan Autoload Dir button in Automation Manager to load the scripts again.
19:53:02: 一个自动化脚本载入失败，文件名： 'C:\DIY\Tools\Aegisub\automation\autoload\CNSpellChecker.lua'，错误报告：
 Error initialising Lua script "CNSpellChecker.lua":

    File "C:/DIY\Tools\Aegisub\automation\autoload\CNSpellChecker.lua", line 7
<main>
    File "<C function>", line -1
?
module 'luajit-request' not found:
	no field package.preload['luajit-request']
	no file '.\luajit-request.dll'
	no file 'C:\DIY\Tools\Aegisub\luajit-request.dll'
	no file 'C:\DIY\Tools\Aegisub\loadall.dll'

**Comment by tianziabcd** [comment]
你好，请帮忙看一个lua脚本，想按500ms分割时间轴，直到不能分为止，目前遇到的问题是，分割出来的时间轴都是一样
请帮忙指点一下



local tr&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;= aegisub.gettext
script_name&nbsp; &nbsp; &nbsp; &nbsp; = tr"分割时间轴"script_description = tr"分割时间轴"script_author&nbsp; &nbsp; &nbsp; = "ABCD"script_version&nbsp; &nbsp; &nbsp;= "1.0"
function charu(subtitles, selected_lines, active_line)	local line_num = #subtitles	local ass_subtitles = {}
	for i = 1, line_num, 1 do		local new1_subtitle = subtitles[i]		if new1_subtitle.class =="dialogue" then			-- 清空对白内容			new1_subtitle.text&nbsp; = ""			-- 设置插轴记号			new1_subtitle.actor = "分割时间轴"			-- 插入时间间隙			if new1_subtitle.end_time - new1_subtitle.start_time &gt; 500 then				local shang = (new1_subtitle.end_time - new1_subtitle.start_time) /500				local cishu = math.floor(shang)				for t = 1, cishu, 1 do				local xishu1 = 1000 * t - 1000				local xishu2 = 1000 * t - 500				new1_subtitle.start_time = new1_subtitle.start_time + xishu1				new1_subtitle.end_time = new1_subtitle.end_time + xishu2				table.insert(ass_subtitles, new1_subtitle)			end		end		table.insert(ass_subtitles, new1_subtitle)		end	end	local ass_subtitles_length = #ass_subtitles	for i = 1, ass_subtitles_length, 1 do		subtitles.append(ass_subtitles[i])	end	aegisub.set_undo_point(script_name)end
aegisub.register_macro(script_name, tr"分割时间轴", charu)分割出来是如下Dialogue: 0,0:00:00.15,0:00:46.25,Default,,0,0,0,,11Dialogue: 0,0:01:42.42,0:01:44.44,Default,,0,0,0,,22Dialogue: 0,0:01:48.42,0:01:52.44,Default,分割时间轴,0,0,0,,Dialogue: 0,0:01:48.42,0:01:52.44,Default,分割时间轴,0,0,0,,Dialogue: 0,0:01:48.42,0:01:52.44,Default,分割时间轴,0,0,0,,Dialogue: 0,0:01:48.42,0:01:52.44,Default,分割时间轴,0,0,0,,Dialogue: 0,0:01:48.42,0:01:52.44,Default,分割时间轴,0,0,0,,Dialogue: 0,0:01:52.56,0:02:52.77,Default,,0,0,0,,33Dialogue: 0,0:02:55.56,0:02:57.04,Default,,0,0,0,,44Dialogue: 0,0:02:56.56,0:02:59.04,Default,分割时间轴,0,0,0,,Dialogue: 0,0:02:56.56,0:02:59.04,Default,分割时间轴,0,0,0,,Dialogue: 0,0:02:56.56,0:02:59.04,Default,分割时间轴,0,0,0,,Dialogue: 0,0:03:01.16,0:03:03.18,Default,,0,0,0,,55Dialogue: 0,0:03:05.70,0:03:07.99,Default,,0,0,0,,66Dialogue: 0,0:03:07.16,0:03:11.18,Default,分割时间轴,0,0,0,,Dialogue: 0,0:03:07.16,0:03:11.18,Default,分割时间轴,0,0,0,,Dialogue: 0,0:03:07.16,0:03:11.18,Default,分割时间轴,0,0,0,,Dialogue: 0,0:03:07.16,0:03:11.18,Default,分割时间轴,0,0,0,,Dialogue: 0,0:03:07.16,0:03:11.18,Default,分割时间轴,0,0,0,,------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qwe7989199/aegisub_scripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 晚上6:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qwe7989199/aegisub_scripts] 请教一下CNSpellChecker.lua依赖怎么用 (Issue #11)





 
Closed #11.

**Comment by tianziabcd** [comment]
谢谢，刚才时间分割脚本已经改正了，打扰了
发件人:                                                                                                                        "qwe7989199/aegisub_scripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 晚上6:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qwe7989199/aegisub_scripts] 请教一下CNSpellChecker.lua依赖怎么用 (Issue #11)





 
Closed #11.
