### ISSUE TITLE
luajit-request.dll和loadall.dll缺失

### ISSUE THREAD

**Issue by ShinodaCronus** [qwe7989199/aegisub_scripts#12]
大佬，[CNSpellChecker.lua] 依赖的的luajit-request.dll和loadall.dll在releases里找不到，可以传一下吗？

**Comment by qwe7989199** [comment]
这是个脚本项目，不是我写的/我修改过的东西是不会上传二进制文件的
依赖的文件在我写的说明有写出链接，可以自行下载需要的版本
https://github.com/LPGhatguy/luajit-request#:~:text=https%3A//curl.haxx.se/download.html
