### ISSUE TITLE
enc-hsub-VS.lua中的mklink需要管理员权限运行

### ISSUE THREAD

**Issue by BingLingGroup** [qwe7989199/aegisub_scripts#3]
https://github.com/qwe7989199/aegisub_scripts/blob/master/autoload/enc-hsub-VS.lua#L291
在使用vsfiltermod时，似乎这两段包含mklink命令的代码需要先用管理员权限运行aegisub，然后我发现aegisub似乎用管理员权限运行就无法把视频用鼠标拖入加载了，是否有必要把mklink改为copy，copy应该不用管理员权限。

**Comment by qwe7989199** [comment]
这里是针对VSFilterMod不支持四字节编码字符的workaround，本意是用资源消耗最小的快捷方式来解决文件名问题。
以后有空会去改改VSFilterMod，治治本，这里就先不动了。
可以用copy先顶着。

**Comment by qwe7989199** [comment]
已经去除了这部分临时文件的相关代码。
解决方式是修改VSFilterMod的源码，实现对文件名/路径的支持，对应的二进制文件：
https://github.com/qwe7989199/aegisub_scripts/tree/master/VSFilterMod_bin
替换掉消极压制64位插件目录下的同名文件即可
