### ISSUE TITLE
Vapoursynth ffms2插件对4K webm的帧率读取有误

### ISSUE THREAD

**Issue by BingLingGroup** [qwe7989199/aegisub_scripts#4]
ffms2似乎会把29.7帧的4K webm(VP9)视频读成32帧，从而导致压制出来的视频音画不同步，如果使用L-SMASH插件就没有这个问题。而脚本中Vapoursynth压制默认是使用ffms2
典型的4K webm(VP9)视频可在youtube上找到
另外Vapoursynth R50似乎不支持自动加载插件了，必须在脚本中手动`core.std.LoadPlugin(...)`才能使用，不太清楚是哪个版本开始要手动加载插件了，不排除可能是我的Vapoursynth出了啥问题

**Comment by qwe7989199** [comment]
实测R50也是能自动读取VS插件目录的。
更新了一下脚本，在缝里抠出来两列把源滤镜选项加进去了。
![pic1](https://user-images.githubusercontent.com/10990771/89706434-95d54c00-d9a0-11ea-948a-ccf144c36784.png)
![pic0](https://user-images.githubusercontent.com/10990771/89706435-97067900-d9a0-11ea-9448-e3c4c82f7bb1.png)

**Comment by BingLingGroup** [comment]
感谢作者添加此功能，那我关issue了

PS: 那看来是我Vapoursynth出啥问题了，害的我还写了个遍历来加载插件，试着重装下吧（躺）

**Comment by BingLingGroup** [comment]
我知道了，大概是因为我之前用的什么上古版本的Vapoursynth，插件目录还是 `C:\Program Files (x86)\VapourSynth\Plugins64` 而不是 `C:\Program Files (x86)\VapourSynth\core\plugins`，所以出了问题
移动插件位置之后就解决了问题
