### ISSUE TITLE
压制双mp4或透明mov报错

### ISSUE THREAD

**Issue by MC-dusk** [qwe7989199/aegisub_scripts#7]
Aegisub 3.2.2 32位64位均尝试过，报错相同
消极压制配置应该无误（VSpipe+x264压制成功）

在图中设定下encode：
![图片](https://user-images.githubusercontent.com/52311860/99530196-f3cff180-29db-11eb-8ccd-4a476afe5437.png)

Lua reported a runtime error:
    File "C:/Program Files (x86)\Aegisub\automation\autoload\enc-hsub-VS.lua", line 397
<anonymous function at lines 75-538>
attempt to index global 'avsfile' (a nil value)

曾经出现过以下报错（具体情况不明）
Lua reported a runtime error:
    File "C:/Program Files (x86)\Aegisub\automation\autoload\enc-hsub-VS.lua", line 396
<anonymous function at lines 75-538>
attempt to concatenate global 'root_path1' (a nil value)

**Comment by MC-dusk** [comment]
换成了更新后的lua脚本，但仍不成功：

```
Active code page: 65001

G:\SPARK-AGAIN>"C:\NegativeEncoder\Libs\ffmpeg.exe" -i "G:\SPARK-AGAIN\sub_alpha.avs" -an -c:v png -r 30.000 -vsync cfr "G:\SPARK-AGAINSPARK-AGAIN NCOP_hardsub_30.000fps_0-2520.mov"
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
G:\SPARK-AGAIN\sub_alpha.avs: Unknown error occurred

G:\SPARK-AGAIN>del "G:\SPARK-AGAIN\sub_alpha.avs"

G:\SPARK-AGAIN>start "" "G:\SPARK-AGAIN"

G:\SPARK-AGAIN>pause
Press any key to continue . . . 

============前者mov========================后者双mp4===================

Active code page: 65001

G:\SPARK-AGAIN>"C:\NegativeEncoder\Libs\ffmpeg.exe" -i "G:\SPARK-AGAIN\sub_alpha.avs" -an -r 23.976 -vsync cfr -filter_complex split[v1][v2];[v2]alphaextract[o2];[v1]format=yuv422p[o1] -map [o1] -g 1 "G:\SPARK-AGAINSPARK-AGAIN NCOP_hardsub_23.976fps_0-2520_sub.mp4" -map [o2] -g 1 "G:\SPARK-AGAINSPARK-AGAIN NCOP_hardsub_23.976fps_0-2520_alpha.mp4"
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
G:\SPARK-AGAIN\sub_alpha.avs: Unknown error occurred

G:\SPARK-AGAIN>del "G:\SPARK-AGAIN\sub_alpha.avs"

G:\SPARK-AGAIN>start "" "G:\SPARK-AGAIN"

G:\SPARK-AGAIN>pause
Press any key to continue . . .
```

**Comment by qwe7989199** [comment]
> 换成了更新后的lua脚本，但仍不成功：
> 
> ```
> Active code page: 65001
> 
> G:\SPARK-AGAIN>"C:\NegativeEncoder\Libs\ffmpeg.exe" -i "G:\SPARK-AGAIN\sub_alpha.avs" -an -c:v png -r 30.000 -vsync cfr "G:\SPARK-AGAINSPARK-AGAIN NCOP_hardsub_30.000fps_0-2520.mov"
> ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
>   built with gcc 8.2.1 (GCC) 20181017
>   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
>   libavutil      56. 22.100 / 56. 22.100
>   libavcodec     58. 35.100 / 58. 35.100
>   libavformat    58. 20.100 / 58. 20.100
>   libavdevice    58.  5.100 / 58.  5.100
>   libavfilter     7. 40.101 /  7. 40.101
>   libswscale      5.  3.100 /  5.  3.100
>   libswresample   3.  3.100 /  3.  3.100
>   libpostproc    55.  3.100 / 55.  3.100
> G:\SPARK-AGAIN\sub_alpha.avs: Unknown error occurred
> 
> G:\SPARK-AGAIN>del "G:\SPARK-AGAIN\sub_alpha.avs"
> 
> G:\SPARK-AGAIN>start "" "G:\SPARK-AGAIN"
> 
> G:\SPARK-AGAIN>pause
> Press any key to continue . . . 
> 
> ============前者mov========================后者双mp4===================
> 
> Active code page: 65001
> 
> G:\SPARK-AGAIN>"C:\NegativeEncoder\Libs\ffmpeg.exe" -i "G:\SPARK-AGAIN\sub_alpha.avs" -an -r 23.976 -vsync cfr -filter_complex split[v1][v2];[v2]alphaextract[o2];[v1]format=yuv422p[o1] -map [o1] -g 1 "G:\SPARK-AGAINSPARK-AGAIN NCOP_hardsub_23.976fps_0-2520_sub.mp4" -map [o2] -g 1 "G:\SPARK-AGAINSPARK-AGAIN NCOP_hardsub_23.976fps_0-2520_alpha.mp4"
> ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
>   built with gcc 8.2.1 (GCC) 20181017
>   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
>   libavutil      56. 22.100 / 56. 22.100
>   libavcodec     58. 35.100 / 58. 35.100
>   libavformat    58. 20.100 / 58. 20.100
>   libavdevice    58.  5.100 / 58.  5.100
>   libavfilter     7. 40.101 /  7. 40.101
>   libswscale      5.  3.100 /  5.  3.100
>   libswresample   3.  3.100 /  3.  3.100
>   libpostproc    55.  3.100 / 55.  3.100
> G:\SPARK-AGAIN\sub_alpha.avs: Unknown error occurred
> 
> G:\SPARK-AGAIN>del "G:\SPARK-AGAIN\sub_alpha.avs"
> 
> G:\SPARK-AGAIN>start "" "G:\SPARK-AGAIN"
> 
> G:\SPARK-AGAIN>pause
> Press any key to continue . . .
> ```

报一下avs版本

**Comment by MC-dusk** [comment]
> 报一下avs版本

AviSynth_260.exe
2.6.0.6
https://sourceforge.net/projects/avisynth2/files/AviSynth%202.6/

**Comment by qwe7989199** [comment]
> > 报一下avs版本
> 
> AviSynth_260.exe
> 2.6.0.6
> https://sourceforge.net/projects/avisynth2/files/AviSynth%202.6/

要求必须是这个64bit版本的，因为ffmpeg是64位的
https://github.com/pinterf/AviSynthPlus/releases/tag/r2772-MT
